openapi: 3.0.0
info:
  title: Health
  version: '1.0'
tags:
  - name: Health
paths:
  /:
    get:
      operationId: HealthController_health1
      description: app health
      parameters: []
      responses:
        '200':
          description: app health successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthOuput'
      tags:
        - Health
  /health:
    get:
      operationId: HealthController_health
      description: app health
      parameters: []
      responses:
        '200':
          description: app health successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthOuput'
      tags:
        - Health
components:
  schemas:
    HealthOuput:
      type: object
      required:
        - server
        - version
        - mongoState
        - redisState
        - postgresState
        - network
        - memory
        - cpu
      properties:
        server:
          type: string
          description: 'application status: **UP** | **DOWN** '
        version:
          type: string
          description: application version
        mongoState:
          type: string
          description: 'mongo status: **UP** | **DOWN** '
        redisState:
          type: string
          description: 'redis status: **UP** | **DOWN** '
        postgresState:
          type: string
          description: 'postgres status: **UP** | **DOWN** '
        network:
          type: object
          properties:
            latency:
              type: string
              description: |2-
                    -- representing the network latency --
                  latency: ** <20  ** status: ** Excellent **

                  latency: ** <100 ** status: ** Acceptable **

                  latency: ** <300 ** status: ** Poor **

                  latency: ** >300 ** status: ** Critical ** 
            connections:
              type: integer
              format: int32
              description: representing the active connections count
          required:
            - latency
            - connections
          description: network information
        memory:
          type: object
          properties:
            process:
              type: object
              properties:
                ramUsed:
                  type: string
                  description: Total memory allocated by the process, including heap, buffers, and native code.
                heapTotal:
                  type: string
                  description: Total heap memory allocated by V8.
                heapUsed:
                  type: string
                  description: Heap memory currently used by V8.
                external:
                  type: string
                  description: Memory allocated outside the V8 heap (e.g., buffers, native bindings).
              required:
                - ramUsed
                - heapTotal
                - heapUsed
                - external
              description: process memory
            v8:
              type: object
              properties:
                totalHeapSize:
                  type: string
                  description: Total heap size managed by V8.
                usedHeapSize:
                  type: string
                  description: Heap size actually being used.
                executableHeapSize:
                  type: string
                  description: Heap size reserved for compiled JavaScript code.
                heapSizeLimit:
                  type: string
                  description: Maximum heap size before memory allocation fails.
              required:
                - totalHeapSize
                - usedHeapSize
                - executableHeapSize
                - heapSizeLimit
              description: v8 memory
          required:
            - process
            - v8
          description: memory usage
        cpu:
          type: object
          properties:
            healthyLimit:
              type: integer
              format: int16
              description: max healthy limit
            loadAverage:
              type: object
              properties:
                lastMinute:
                  allOf:
                    - $ref: '#/components/schemas/HealthOuputLoad'
                  description: cpu load average on last minute
                lastFiveMinutes:
                  allOf:
                    - $ref: '#/components/schemas/HealthOuputLoad'
                  description: cpu load average on five minute
                lastFifteenMinutes:
                  allOf:
                    - $ref: '#/components/schemas/HealthOuputLoad'
                  description: cpu load average on fifteen minute
              required:
                - lastMinute
                - lastFiveMinutes
                - lastFifteenMinutes
              description: cpu load average
          required:
            - healthyLimit
            - loadAverage
          description: cpu usage
      description: health output
    HealthOuputLoad:
      type: object
      required:
        - load
        - status
      properties:
        load:
          type: number
          format: decimal
          description: load avererage
        status:
          type: string
          description: load avererage status **healthy** | **overloaded**
      description: load avererage
