openapi: 3.0.0
info:
  title: Logout
  version: v2
tags:
  - name: Logout
paths:
  /api/{version}/logout:
    post:
      operationId: LogoutController_logout
      description: user logout
      parameters:
        - $ref: '#/components/parameters/api.Utils.Versions.VersionParams'
      responses:
        '200':
          description: user logout successfully
        '400':
          description: When input is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutValidationError'
      tags:
        - Logout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutInput'
      security:
        - BearerAuth: []
components:
  parameters:
    api.Utils.Versions.VersionParams:
      name: version
      in: path
      required: true
      description: route version
      schema:
        $ref: '#/components/schemas/api.Utils.Versions.Versions'
  schemas:
    LogoutInput:
      type: object
      required:
        - token
      properties:
        token:
          type: string
      description: logout input
    LogoutValidationError:
      type: object
      allOf:
        - type: object
          required:
            - error
          properties:
            error:
              type: object
              required:
                - code
                - traceid
                - context
                - message
                - timestamp
                - path
              properties:
                code:
                  type: number
                  enum:
                    - 400
                  description: status code
                traceid:
                  type: string
                  description: request traceid
                context:
                  type: string
                  description: class that error occur
                message:
                  type: array
                  items:
                    type: string
                    enum:
                      - 'token: Required'
                  description: error message
                timestamp:
                  type: string
                  description: timestamp that error occur
                path:
                  type: string
                  description: path error
              description: default error model
          description: When input is invalid.
      description: When input is invalid
    api.Utils.Versions.Versions:
      type: string
      enum:
        - v1
        - v2
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
